/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as English_lessonRouteImport } from './routes/english_lesson'
import { Route as Drawing_gamesRouteImport } from './routes/drawing_games'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DrawSlugRouteImport } from './routes/draw.$slug'

const English_lessonRoute = English_lessonRouteImport.update({
  id: '/english_lesson',
  path: '/english_lesson',
  getParentRoute: () => rootRouteImport,
} as any)
const Drawing_gamesRoute = Drawing_gamesRouteImport.update({
  id: '/drawing_games',
  path: '/drawing_games',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawSlugRoute = DrawSlugRouteImport.update({
  id: '/draw/$slug',
  path: '/draw/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drawing_games': typeof Drawing_gamesRoute
  '/english_lesson': typeof English_lessonRoute
  '/draw/$slug': typeof DrawSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drawing_games': typeof Drawing_gamesRoute
  '/english_lesson': typeof English_lessonRoute
  '/draw/$slug': typeof DrawSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drawing_games': typeof Drawing_gamesRoute
  '/english_lesson': typeof English_lessonRoute
  '/draw/$slug': typeof DrawSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/drawing_games' | '/english_lesson' | '/draw/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/drawing_games' | '/english_lesson' | '/draw/$slug'
  id: '__root__' | '/' | '/drawing_games' | '/english_lesson' | '/draw/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Drawing_gamesRoute: typeof Drawing_gamesRoute
  English_lessonRoute: typeof English_lessonRoute
  DrawSlugRoute: typeof DrawSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/english_lesson': {
      id: '/english_lesson'
      path: '/english_lesson'
      fullPath: '/english_lesson'
      preLoaderRoute: typeof English_lessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawing_games': {
      id: '/drawing_games'
      path: '/drawing_games'
      fullPath: '/drawing_games'
      preLoaderRoute: typeof Drawing_gamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draw/$slug': {
      id: '/draw/$slug'
      path: '/draw/$slug'
      fullPath: '/draw/$slug'
      preLoaderRoute: typeof DrawSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Drawing_gamesRoute: Drawing_gamesRoute,
  English_lessonRoute: English_lessonRoute,
  DrawSlugRoute: DrawSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
